--[[  
    Welcome to the default Crafting configuration!
    Run this system as you like, you have the possibility to use props to 
    go and craft and even a specific point for crafting weapon accessories.

    Remember that you can add certain items with different crafting timers 
    in Config.CustomCraftItemTimers.

    You can use the threshold setting as a level requirement system!
    You can modify the item info in client/custom/misc/CraftingInfo.lua.
]]

Config.CustomCraftItemTimers = {
    ['weapon_combatpistol'] = 5000,
    ['weapon_machinepistol'] = 6000, 
    ['weapon_pistol50'] = 7000, 
    ['weapon_vintagepistol'] = 8000, 
    ['weapon_gusenberg'] = 9000, 
    ['weapon_minismg'] = 10000, 
    ['weapon_revolver'] = 11000, 
    ['weapon_microsmg'] = 12000, 
    ['weapon_marksmanpistol'] = 13000, 
    ['weapon_combatpdw'] = 14000, 
    ['weapon_assaultsmg'] = 15000, 
    ['weapon_sawnoffshotgun'] = 16000, 
    ['weapon_assaultshotgun'] = 18000, 
    ['weapon_compactrifle'] = 19000, 
    ['weapon_specialcarbine'] = 20000, 
    ['weapon_bullpuprifle'] = 21000, 
    ['weapon_assaultrifle'] = 22000, 
    ['weapon_assaultrifle_mk2'] = 23000, 
    ['punho'] = 5000, 
    ['50rddrum'] = 5000, 
    ['estruturadeagle'] = 5000, 
    ['estruturarevolver'] = 5000, 
    ['canopistola'] = 5000, 
    ['estruturapistola'] = 5000, 
    ['magazinepistola'] = 5000, 
    ['canosmg'] = 5000, 
    ['estruturasmg'] = 5000, 
    ['magazinesmg'] = 5000, 
    ['coronhasmg'] = 5000, 
    ['canorifle'] = 5000, 
    ['estruturarifle'] = 5000, 
    ['magazinerifle'] = 5000, 
    ['coronharifle'] = 5000, 
    ['canoshotgun'] = 5000, 
    ['estruturashotgun'] = 5000, 
    ['magazineshotgun'] = 5000, 
}

Config.CraftingObject = `prop_toolchest_05`
Config.AttachmentCraftingLocation = vector3(88.91, 3743.88, 40.77)

Config.CraftingItems = {
    --[[
	[1] = {
		name = "weapon_combatpistol",
		amount = 1,
		info = {},
		costs = {
			["canopistola"] = 1,
			["magazinepistola"] = 1,
			["estruturapistola"] = 1,
			["punho"] = 1,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 1,
		threshold = 0,
		points = 1,
	},
	[2] = {
		name = "weapon_machinepistol",
		amount = 1,
		info = {},
		costs = {
			["canopistola"] = 1,
			["magazinepistola"] = 2,
			["estruturapistola"] = 1,
			["punho"] = 1,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 2,
		threshold = 0,
		points = 2,
	},
	[3] = {
		name = "weapon_pistol50",
		amount = 1,
		info = {},
		costs = {
			["canopistola"] = 2,
			["estruturadeagle"] = 1,
			["magazinepistola"] = 1,
			["punho"] = 2,
			["50rddrum"] = 2,
		},
		type = "item",
		slot = 3,
		threshold = 0,
		points = 3,
	},
	[4] = {
		name = "weapon_vintagepistol",
		amount = 1,
		info = {},
		costs = {
			["canopistola"] = 2,
			["estruturapistola"] = 1,
			["magazinepistola"] = 2,
			["punho"] = 1,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 4,
		threshold = 0,
		points = 4,
	},
	[5] = {
		name = "weapon_gusenberg",
		amount = 1,
		info = {},
		costs = {
			["canosmg"] = 1,
			["coronhasmg"] = 2,
			["50rddrum"] = 1,
			["estruturasmg"] = 1,
			["magazinesmg"] = 2,
			["punho"] = 1,
		},
		type = "item",
		slot = 5,
		threshold = 120,
		points = 5,
	},
	[6] = {
		name = "weapon_minismg",
		amount = 1,
		info = {},
		costs = {
			["canosmg"] = 1,
			["estruturasmg"] = 2,
			["coronhasmg"] = 1,
			["magazinesmg"] = 2,
			["punho"] = 2,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 6,
		threshold = 160,
		points = 6,
	},
	[7] = {
		name = "weapon_revolver",
		amount = 1,
		info = {},
		costs = {
			["canopistola"] = 2,
			["estruturarevolver"] = 1,
			["magazinepistola"] = 2,
			["punho"] = 1,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 7,
		threshold = 200,
		points = 7,
	},
	[8] = {
		name = "weapon_marksmanpistol",
		amount = 1,
		info = {},
		costs = {
			["canopistola"] = 1,
			["magazinepistola"] = 2,
			["estruturarevolver"] = 1,
			["punho"] = 1,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 8,
		threshold = 250,
		points = 8,
	},
	[9] = {
		name = "weapon_microsmg",
		amount = 1,
		info = {},
		costs = {
			["canosmg"] = 2,
			["estruturasmg"] = 1,
			["magazinesmg"] = 2,
			["coronhasmg"] = 1,
			["punho"] = 2,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 9,
		threshold = 300,
		points = 9,
	},
	[10] = {
		name = "weapon_combatpdw",
		amount = 1,
		info = {},
		costs = {
			["canosmg"] = 2,
			["estruturasmg"] = 1,
			["magazinesmg"] = 2,
			["coronhasmg"] = 1,
			["punho"] = 1,
			["50rddrum"] = 2,
		},
		type = "item",
		slot = 10,
		threshold = 300,
		points = 10,
	},
	[11] = {
		name = "weapon_assaultsmg",
		amount = 1,
		info = {},
		costs = {
			["canosmg"] = 2,
			["estruturasmg"] = 2,
			["magazinesmg"] = 2,
			["coronhasmg"] = 1,
			["punho"] = 2,
			["50rddrum"] = 2,
		},
		type = "item",
		slot = 11,
		threshold = 350,
		points = 11,
	},
	[12] = {
		name = "weapon_sawnoffshotgun",
		amount = 1,
		info = {},
		costs = {
			["canoshotgun"] = 1,
			["estruturashotgun"] = 1,
			["magazineshotgun"] = 1,
			["punho"] = 2,
			["50rddrum"] = 1,
		},
		type = "item",
		slot = 12,
		threshold = 1750,
		points = 12,
	},
	[13] = {
		name = "weapon_assaultshotgun",
		amount = 1,
		info = {},
		costs = {
			["canoshotgun"] = 1,
			["estruturashotgun"] = 2,
			["magazineshotgun"] = 1,
			["punho"] = 3,
			["50rddrum"] = 3,
		},
		type = "item",
		slot = 13,
		threshold = 1750,
		points = 13,
	},
	[14] = {
		name = "weapon_compactrifle",
		amount = 1,
		info = {},
		costs = {
			["estruturarifle"] = 1,
			["magazinerifle"] = 1,
			["coronharifle"] = 1,
			["canorifle"] = 1,
			["punho"] = 3,
			["50rddrum"] = 3,
		},
		type = "item",
		slot = 14,
		threshold = 1750,
		points = 14,
	},
	[15] = {
		name = "weapon_specialcarbine",
		amount = 1,
		info = {},
		costs = {
			["canorifle"] = 1,
			["estruturarifle"] = 2,
			["magazinerifle"] = 1,
			["coronharifle"] = 1,
			["punho"] = 1,
			["50rddrum"] = 2,
		},
		type = "item",
		slot = 15,
		threshold = 1750,
		points = 15,
	},
	[16] = {
		name = "weapon_bullpuprifle",
		amount = 1,
		info = {},
		costs = {
			["canorifle"] = 1,
			["estruturarifle"] = 1,
			["magazinerifle"] = 1,
			["coronharifle"] = 1,
			["punho"] = 3,
			["50rddrum"] = 3,
		},
		type = "item",
		slot = 16,
		threshold = 1750,
		points = 16,
	},
	[17] = {
		name = "weapon_assaultrifle",
		amount = 1,
		info = {},
		costs = {
			["canorifle"] = 2,
			["estruturarifle"] = 1,
			["magazinerifle"] = 1,
			["coronharifle"] = 1,
			["punho"] = 2,
			["50rddrum"] = 3,
		},
		type = "item",
		slot = 17,
		threshold = 1750,
		points = 17,
	},
	[18] = {
		name = "weapon_assaultrifle_mk2",
		amount = 1,
		info = {},
		costs = {
			["canorifle"] = 2,
			["estruturarifle"] = 2,
			["magazinerifle"] = 1,
			["coronharifle"] = 1,
			["punho"] = 3,
			["50rddrum"] = 2,
		},
		type = "item",
		slot = 18,
		threshold = 1750,
		points = 18,
	},
	[19] = {
		name = "punho",
		amount = 1,
		info = {},
		costs = {
			["glass"] = 20,
			["plastic"] = 30,
			["gold"] = 1,
		},
		type = "item",
		slot = 19,
		threshold = 0,
		points = 1,
	},
	[20] = {
		name = "50rddrum",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 2,
			["gold"] = 5,
			["aluminium"] = 15,
			["metal"] = 30,
		},
		type = "item",
		slot = 20,
		threshold = 0,
		points = 2,
	},
	[21] = {
		name = "estruturadeagle",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 2,
			["aluminium"] = 5,
			["glass"] = 20,
			["metal"] = 30,
		},
		type = "item",
		slot = 21,
		threshold = 0,
		points = 3,
	},
	[22] = {
		name = "estruturarevolver",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 2,
			["aluminium"] = 5,
			["steel"] = 10,
			["metal"] = 30,
			["copper"] = 6,
			["gold"] = 2,
		},
		type = "item",
		slot = 22,
		threshold = 0,
		points = 4,
	},
	[23] = {
		name = "canopistola",
		amount = 1,
		info = {},
		costs = {
			["plastic"] = 2,
			["steel"] = 10,
			["iron"] = 3,
		},
		type = "item",
		slot = 23,
		threshold = 120,
		points = 5,
	},
	[24] = {
		name = "estruturapistola",
		amount = 1,
		info = {},
		costs = {
			["plastic"] = 5,
			["steel"] = 20,
			["iron"] = 6,
			["rubber"] = 14,
			["glass"] = 4,
			["copper"] = 3,
		},
		type = "item",
		slot = 24,
		threshold = 160,
		points = 6,
	},
	[25] = {
		name = "magazinepistola",
		amount = 1,
		info = {},
		costs = {
			["plastic"] = 2,
			["steel"] = 10,
			["iron"] = 3,
		},
		type = "item",
		slot = 25,
		threshold = 200,
		points = 7,
	},
	[26] = {
		name = "canosmg",
		amount = 1,
		info = {},
		costs = {
			["plastic"] = 2,
			["steel"] = 10,
			["iron"] = 3,
			["gold"] = 1,
			["aluminium"] = 2,
			["glass"] = 4,
		},
		type = "item",
		slot = 26,
		threshold = 250,
		points = 8,
	},
	[27] = {
		name = "estruturasmg",
		amount = 1,
		info = {},
		costs = {
			["plastic"] = 12,
			["steel"] = 20,
			["iron"] = 3,
			["gold"] = 2,
			["aluminium"] = 5,
			["glass"] = 20,
			["copper"] = 6,
		},
		type = "item",
		slot = 27,
		threshold = 300,
		points = 9,
	},
	[28] = {
		name = "magazinesmg",
		amount = 1,
		info = {},
		costs = {
			["plastic"] = 10,
			["steel"] = 10,
			["iron"] = 3,
			["gold"] = 1,
			["aluminium"] = 2,
		},
		type = "item",
		slot = 28,
		threshold = 300,
		points = 10,
	},
	[29] = {
		name = "coronhasmg",
		amount = 1,
		info = {},
		costs = {
			["plastic"] = 5,
			["steel"] = 15,
			["iron"] = 6,
			["copper"] = 3,
			["rubber"] = 14,
			["glass"] = 4,
		},
		type = "item",
		slot = 29,
		threshold = 350,
		points = 11,
	},
	[30] = {
		name = "canorifle",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 5,
			["gold"] = 25,
			["iron"] = 10,
			["copper"] = 5,
			["aluminium"] = 5,
			["steel"] = 20,
		},
		type = "item",
		slot = 30,
		threshold = 1750,
		points = 12,
	},
	[31] = {
		name = "estruturarifle",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 5,
			["gold"] = 25,
			["iron"] = 5,
			["copper"] = 5,
			["aluminium"] = 5,
			["steel"] = 20,
			["glass"] = 10,
		},
		type = "item",
		slot = 31,
		threshold = 1750,
		points = 13,
	},
	[32] = {
		name = "magazinerifle",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 5,
			["gold"] = 20,
			["steel"] = 10,
		},
		type = "item",
		slot = 32,
		threshold = 1750,
		points = 14,
	},
	[33] = {
		name = "coronharifle",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 2,
			["gold"] = 7,
			["steel"] = 15,
			["copper"] = 5,
			["metal"] = 3,
			["rubber"] = 3,
		},
		type = "item",
		slot = 33,
		threshold = 1750,
		points = 15,
	},
	[34] = {
		name = "canoshotgun",
		amount = 1,
		info = {},
		costs = {
			["iron"] = 8,
			["gold"] = 6, 
			["steel"] = 20, 
			["copper"] = 7, 
			["copper"] = 7, 
			["aluminium"] = 5,
		},
		type = "item",
		slot = 34,
		threshold = 1750,
		points = 16,
	},
	[35] = {
		name = "estruturashotgun",
		amount = 1,
		info = {},
		costs = {
			["diamond"] = 5,
			["gold"] = 27, 
			["steel"] = 20, 
			["copper"] = 5, 
			["iron"] = 20, 
			["aluminium"] = 5, 
		},
		type = "item",
		slot = 35,
		threshold = 1750,
		points = 17,
	},
	[36] = {
		name = "magazineshotgun",
		amount = 1,
		info = {},
		costs = {
			["glass"] = 20,
			["gold"] = 4, 
			["steel"] = 20, 
			["iron"] = 8, 
			["rubber"] = 10, 
			["metal"] = 10, 
		},
		type = "item",
		slot = 36,
		threshold = 1750,
		points = 18,
	},
	--]]
}

Config.AttachmentCrafting = {
    ['items'] = {
        [1] = {
            name = 'pistol_extendedclip',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 140,
                ['steel'] = 250,
                ['rubber'] = 60,
            },
            type = 'item',
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = 'pistol_suppressor',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 165,
                ['steel'] = 285,
                ['rubber'] = 75,
            },
            type = 'item',
            slot = 2,
            threshold = 0,
            points = 2,
        },
        [3] = {
            name = 'smg_extendedclip',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 190,
                ['steel'] = 305,
                ['rubber'] = 85,
            },
            type = 'item',
            slot = 3,
            threshold = 25,
            points = 3,
        },
        [4] = {
            name = 'microsmg_extendedclip',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 205,
                ['steel'] = 340,
                ['rubber'] = 110,
            },
            type = 'item',
            slot = 4,
            threshold = 50,
            points = 4,
        },
        [5] = {
            name = 'smg_drum',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 230,
                ['steel'] = 365,
                ['rubber'] = 130,
            },
            type = 'item',
            slot = 5,
            threshold = 75,
            points = 5,
        },
        [6] = {
            name = 'smg_scope',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 255,
                ['steel'] = 390,
                ['rubber'] = 145,
            },
            type = 'item',
            slot = 6,
            threshold = 100,
            points = 6,
        },
        [7] = {
            name = 'assaultrifle_extendedclip',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 270,
                ['steel'] = 435,
                ['rubber'] = 155,
                ['smg_extendedclip'] = 1,
            },
            type = 'item',
            slot = 7,
            threshold = 150,
            points = 7,
        },
        [8] = {
            name = 'assaultrifle_drum',
            amount = 50,
            info = {},
            costs = {
                ['metalscrap'] = 300,
                ['steel'] = 469,
                ['rubber'] = 170,
                ['smg_extendedclip'] = 2,
            },
            type = 'item',
            slot = 8,
            threshold = 200,
            points = 8,
        },
    }
}