
--░██████╗██╗░░██╗░█████╗░██████╗░░██████╗
--██╔════╝██║░░██║██╔══██╗██╔══██╗██╔════╝
--╚█████╗░███████║██║░░██║██████╔╝╚█████╗░
--░╚═══██╗██╔══██║██║░░██║██╔═══╝░░╚═══██╗
--██████╔╝██║░░██║╚█████╔╝██║░░░░░██████╔╝
--╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░╚═════╝░

Config.WeaponLicense = 'license' -- Select between 'item' (qs-licenses) or 'license' (esx_license) system
Config.esx_licensecheckLicense = "esx_license:checkLicense"

Config.Shops = {

    ['Market'] = {
        label = "Market",
        coords = {
            vector3(26.31622, -1346.62, 29.496), --1
            vector3(374.5134, 326.7786, 103.56), --2
            vector3(2556.059, 382.6560, 108.62), --3
            vector3(-3040.50, 585.9374, 7.9088), --4
            vector3(-3242.92, 1001.855, 12.830), --5
            vector3(547.3999, 2670.186, 42.156), --6
            vector3(1961.259, 3741.599, 32.343), --7
            vector3(2678.916, 3280.671, 55.241), --8
            vector3(1729.563, 6414.126, 35.037), --9
            vector3(-48.519, -1757.514, 29.421), --10
            vector3(1163.373, -323.801, 69.205), --11
            vector3(-707.501, -914.260, 19.215), --12
            vector3(-1820.523, 792.518, 138.118), --13
            vector3(1698.388, 4924.404, 42.063), --14
            vector3(1135.808, -982.281, 46.415), --15
            vector3(-1487.553, -379.107, 40.163), --16
            vector3(-2968.243, 390.910, 15.043), --17
            vector3(1166.024, 2708.930, 38.157), --18
            vector3(1392.562, 3604.684, 34.980), --19
			vector3(4468.0, -4464.96, 4.2469), --20
        },
        Shop = {
            items = {
                 [1] = {
					name = "water",
					price = 10,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},   
				[2] = {
					name = "milk",
					price = 15,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				}, 
				[3] = {
					name = "bread",
					price = 10,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "sandwich",
					price = 20,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "chocolate",
					price = 20,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "bandage",
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				}, 
				[7] = {
					name = "contract",
					price = 20000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				}, 
				[8] = {
					name = "fixtool",
					price = 8000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 8,
				}, 
				[9] = {
					name = "tyrekit",
					price = 5000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				}, 
				[10] = {
					name = "binoculars",
					price = 100,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				}, 
				[11] = {
					name = "lighter",
					price = 20,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				}, 
				[12] = {
					name = "cigarett",
					price = 50,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "book",
					price = 60,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "picareta",
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = "backpack",
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = "briefcase",
					price = 50000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 16,
				},    
            },
			markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Loja',
            blip = {id = 59, scale = 0.6, color = 2, title = 'Minimercado'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },

    ['Ammunation'] = {
        label = "Ammunation",
        coords = {
             vector3(-660.897, -939.515, 21.829),
            vector3(814.67, -2153.3, 29.6),
            vector3(1696.614, 3756.295, 34.705),
            vector3(-327.541, 6080.239, 31.454),
            vector3(247.9127, -49.8602, 69.941),
            vector3(16.37532, -1109.93, 29.797),
            vector3(2566.883, 298.3731, 108.73),
            vector3(-1114.18, 2696.219, 18.554),
            vector3(843.4, -1029.71, 28.1),
            vector3(-1309.77, -392.512, 36.695),
        },
        Shop = {
            items = {
                [1] = {
					name = "weapon_pistol",
					label = "Taurus PT92",
					price = 120000,
					amount = 3000,
					info = {},
					type = "weapon",
					slot = 1,
				},
				[2] = {
					name = 'WEAPON_SNSPISTOL',
					label = 'Pistola SNS',
					price = 100000,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 2,
				},
				[3] = {
					name = "weapon_knife",
					label = "Faca",
					price = 30000,
					amount = 1,
					info = {},
					type = "weapon",
					slot = 3,
				},
				[4] = {
					name = 'weapon_switchblade',
					label = 'Canivete',
					price = 20000,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 4,
				},
				[5] = {
					name = "weapon_crowbar",
					label = "Pé de Cabra",
					price = 10000,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 5,
				},   
				[6] = {
					name = "weapon_bat",
					label = "Bastão",
					price = 10000,
					amount = 1,
					info = {},
					type = "weapon",
					slot = 6,
				},
				[7] = {
					name = 'WEAPON_HAMMER',
					label = 'Martelo',
					price = 10000,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 7,
				},
				[8] = {
					name = 'WEAPON_KNUCKLE',
					label = 'Soco Inglês',
					price = 10000,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 8,
				},
				[9] = {
					name = 'pistol_ammo',
					label = 'Munição de Pistola',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "green_weapontint",
					label = "Pintura Verde",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "gold_weapontint",
					label = "Pintura Dourada",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "pink_weapontint",
					label = "Pintura Rosa",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "army_weapontint",
					label = "Pintura Exército",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "lspd_weapontint",
					label = "Pintura Policia",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = "orange_weapontint",
					label = "Tinta Laranja",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = "plat_weapontint",
					label = "Tinta Platína",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 16,
				},
				[17] = {
					name = "knuckle_style_1",
					label = "The Pimp",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 17,
				},
				[18] = {
					name = "knuckle_style_2",
					label = "The Ballas",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 18,
				},
				[19] = {
					name = "knuckle_style_3",
					label = "The Hustler",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 19,
				},
				[20] = {
					name = "knuckle_style_4",
					label = "The Rock",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 20,
				},
				[21] = {
					name = "knuckle_style_5",
					label = "The Hater",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 21,
				},
				[22] = {
					name = "knuckle_style_6",
					label = "The Lover",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 22,
				},
				[23] = {
					name = "knuckle_style_7",
					label = "The Player",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 23,
				},
				[24] = {
					name = "knuckle_style_8",
					label = "The King",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 24,
				},
				[25] = {
					name = "knuckle_style_9",
					label = "The Vagos",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 25,
				},
				[26] = {
					name = "blade_style_1",
					label = "Luxury",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 26,
				},
				[27] = {
					name = "blade_style_2",
					label = "Bodyguard",
					price = 1000,
					amount = 99,
					info = {},
					type = "item",
					slot = 27,
				},
				[28] = {
					name = 'WEAPON_FLASHLIGHT',
					label = 'Lanterna',
					price = 7000,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 28,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Ammunation',
            blip = {id = 110, scale = 0.8, color = 26, title = 'Ammunation'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = 'weapon', -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença de porte de arma!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },

    ['LojaHardware'] = {
        label = "Loja de Hardware",
        coords = {
            vector3(45.68, -1749.04, 29.61),
            vector3(2747.71, 3472.85, 55.67),
            vector3(-421.83, 6136.13, 31.88),
        },
        Shop = {
            items = {
				[1] = {
					name = 'sim_card',
					label = 'Cartão SIM',
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
                [2] = {
					name = "classic_phone",
					label = 'Iphone 13 Cinzento',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "black_phone",
					label = 'Iphone 13 Preto',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				}, 
				[4] = {
					name = 'blue_phone',
					label = 'Iphone 13 Azul',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = 'gold_phone',
					label = 'Iphone 13 Dourado',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = 'red_phone',
					label = 'Iphone 13 Vermelho',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = 'green_phone',
					label = 'Iphone 13 Verde',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = 'greenlight_phone',
					label = 'Iphone 13 Lima',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = 'pink_phone',
					label = 'Iphone 13 Rosa',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = 'white_phone',
					label = 'Iphone 13 Branco',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = 'radio',
					label = 'Walkie Talkie',
					price = 1500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = 'phone_module',
					label = 'Módulo para Iphone 113',
					price = 700,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = 'powerbank',
					label = 'Carregador Portátil',
					price = 50,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = 'laptop',
					label = 'Computador',
					price = 5000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Loja de Hardware',
            blip = {id = 521, scale = 0.6, color = 1, title = 'Loja de Hardware'}, --or false,
            job = {'all'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['LojaCaca'] = {
        label = "Loja de Caça",
        coords = {
            vector3(-675.25, 5836.27, 17.34)
        },
        Shop = {
            items = {
                [1] = {
					name = "WEAPON_MUSKET",
					label = 'Mosquete',
					price = 30000,
					amount = 100,
					info = {},
					type = "weapon",
					slot = 1,
				},
				[2] = {
					name = "shotgun_ammo",
					label = 'Munição de Shotgun',
					price = 1000,
					amount = 100,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "weapon_knife",
					label = 'Faca',
					price = 5000,
					amount = 100,
					info = {},
					type = "weapon",
					slot = 3,
				},				
				[4] = {
					name = "animal_bait",
					label = 'Bait de Animal',
					price = 1000,
					amount = 500,
					info = {},
					type = "item",
					slot = 4,
				}, 
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
			type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Loja de Caça',
            blip = {id = 470, scale = 0.7, color = 5, title = 'Loja de Caça'}, --or false,
            job = {'all'},
            grade = {'all'},
			license = 'hunt', -- Require license or not (false or the name of the license)
			licenseError = 'Tens que ter uma licença de caça!',
			distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['LojaWeed'] = {
        label = "Loja de Weed",
        coords = {
            vector3(-1168.26, -1573.2, 4.66)
        },
        Shop = {
            items = {
                [1] = {
					name = 'weed_nutrition',
					price = 100,
					amount = 50,
					info = {},
					type = 'item',
					slot = 1,
				},
				[2] = {
					name = 'empty_weed_bag',
					price = 100,
					amount = 1000,
					info = {},
					type = 'item',
					slot = 2,
				},
				[3] = {
					name = 'weed_white-widow_seed',
					price = 50,
					amount = 1000,
					info = {},
					type = 'item',
					slot = 3,
				},
				[4] = {
					name = 'weed_skunk_seed',
					price = 50,
					amount = 1000,
					info = {},
					type = 'item',
					slot = 4,
				},
				[5] = {
					name = 'weed_purple-haze_seed',
					price = 50,
					amount = 1000,
					info = {},
					type = 'item',
					slot = 5,
				},
				[6] = {
					name = 'weed_og-kush_seed',
					price = 50,
					amount = 1000,
					info = {},
					type = 'item',
					slot = 6,
				},
				[7] = {
					name = 'weed_amnesia_seed',
					price = 50,
					amount = 1000,
					info = {},
					type = 'item',
					slot = 7,
				},
				[8] = {
					name = 'weed_ak47_seed',
					price = 50,
					amount = 1000,
					info = {},
					type = 'item',
					slot = 8,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
			type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Loja de Weed',
            blip = {id = 140, scale = 0.7, color = 0, title = 'Loja de Weed'}, --or false,
            job = {'all'},
            grade = {'all'},
			license = false, -- Require license or not (false or the name of the license)
			licenseError = 'Tens que ter uma licença de weed!',
			distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['LojaPesca'] = {
        label = "Loja de Pesca",
        coords = {
            vector3(-1599.32, 5201.53, 4.2),
            vector3(4818.71, -4309.48, 5.70)
        },
        Shop = {
            items = {
                [1] = {
					name = "fishingrod",
					label = 'Cana de Pesca',
					price = 400,
					amount = 2000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "fishbait",
					label = 'Isca de Pesca',
					price = 10,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "turtlebait",
					label = 'Isca de Tartaruga',
					price = 20,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "anchor",
					label = 'Âncora',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},				
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
			type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Loja de Pesca',
            blip = {id = 317, scale = 0.9, color = 29, title = 'Loja de Pesca'}, --or false,
            job = {'all'},
            grade = {'all'},
			license = false, -- Require license or not (false or the name of the license)
			licenseError = 'Tens que ter uma licença!',
			distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['ArsenalPSP'] = {
        label = "Arsenal",
        coords = {
            vector3(482.31, -996.05, 30.69), -- central
           -- vector3(484.7, -1006.08, 25.73), -- los santos
           -- vector3(1841.98, 3690.4, 34.26), -- centro
            vector3(-437.71, 5988.39, 31.72), -- norte
        },
        Shop = {
            items = {
                [1] = {
					name = "weapon_nightstick",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "weapon_stungun",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "weapon_combatpistol",
					price = 0,
					amount = 9999999,
					info = {
						ammo = "80",
						--attachments = {
						--    {component = "COMPONENT_AT_PI_SUPP", label = "Silenciador"},
						--    {component = "COMPONENT_COMBATPISTOL_CLIP_02", label = "Carregador Extendido"},
						--    {component = "COMPONENT_AT_PI_FLSH", label = "Lanterna"},
						--}
					},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "weapon_smg",
					price = 0,
					amount = 9999999,
					info = {
						ammo = "120",
						--attachments = {
						--    {component = "COMPONENT_AT_SCOPE_MACRO_02", label = "Mira"},
						--    {component = "COMPONENT_AT_AR_FLSH", label = "Lanterna"},
						--}
					},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "weapon_pumpshotgun",
					price = 0,
					amount = 9999999,
					info = {
						ammo = "120",
						--attachments = {
						--    {component = "COMPONENT_AT_SR_SUPP", label = "Silenciador"},
						--    {component = "COMPONENT_AT_AR_FLSH", label = "Lanterna"},
						--}
					},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "weapon_carbinerifle",
					price = 0,
					amount = 9999999,
					info = {
						ammo = "250",
						--attachments = {
						--    {component = "COMPONENT_AT_AR_SUPP", label = "Silenciador"},
						--    {component = "COMPONENT_CARBINERIFLE_CLIP_02", label = "Carregador Extendido"},
						--    {component = "COMPONENT_AT_SCOPE_MEDIUM", label = "Mira"},
						--    {component = "COMPONENT_AT_AR_FLSH", label = "Lanterna"},
						--}
					},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = "weapon_carbinerifle_mk2",
					price = 0,
					amount = 9999999,
					info = {
						ammo = "250",
						--attachments = {
						--    {component = "COMPONENT_AT_AR_SUPP", label = "Silenciador"},
						--    {component = "COMPONENT_CARBINERIFLE_MK2_CLIP_02", label = "Carregador Extendido"},
						--    {component = "COMPONENT_AT_AR_AFGRIP_02", label = "Grip"},
						--    {component = "COMPONENT_AT_SCOPE_MEDIUM_MK2", label = "Mira"},
						--    {component = "COMPONENT_AT_AR_FLSH", label = "Lanterna"},
						--    {component = "COMPONENT_CARBINERIFLE_MK2_CAMO_04", label = "Tinta"},
						--}
					},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = "weapon_sniperrifle",
					price = 0,
					amount = 9999999,
					info = {
						ammo = "120",
					--    attachments = {
					--        {component = "COMPONENT_AT_AR_SUPP_02", label = "Silenciador"},
					--        {component = "COMPONENT_AT_SCOPE_MAX", label = "Mira Avançada"},
					--    }
					},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = "weapon_fireextinguisher",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "weapon_flaregun",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "pistol_ammo",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "smg_ammo",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "shotgun_ammo",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "sniper_ammo",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = "rifle_ammo",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = "pistol_suppressor",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 16,
				},
				[17] = {
					name = "pistol_extendedclip",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 17,
				},
				[18] = {
					name = "pistol_flashlight",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 18,
				},
				[19] = {
					name = "smg_suppressor",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 19,
				},
				[20] = {
					name = "smg_extendedclip",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 20,
				},
				[21] = {
					name = "smg_flashlight",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 21,
				},
				[22] = {
					name = "smg_grip",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 22,
				},
				[23] = {
					name = "smg_scope",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 23,
				},
				[24] = {
					name = "smg_drummag",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 24,
				},
				[25] = {
					name = "rifle_extendedclip",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 25,
				},
				[26] = {
					name = "rifle_drummag",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 26,
				},
				[27] = {
					name = "rifle_flashlight",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 27,
				},
				[28] = {
					name = "rifle_scope",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 28,
				},
				[29] = {
					name = "rifle_grip",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 29,
				},
				[30] = {
					name = "rifle_suppressor",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 30,
				},
				[31] = {
					name = "sniper_suppressor",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 31,
				},
				[32] = {
					name = "sniper_scope",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 32,
				},
				--[[
				[33] = {
					name = "sniper_advancedscope",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 33,
				},
				--]]
				[33] = {
					name = "sniper_grip",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 33,
				},
				--[[
				[35] = {
					name = "sniper_extendedclip",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 35,
				},
				--]]
				[34] = {
					name = "sniper_flashlight",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 34,
				},
				[35] = {
					name = "heavyarmor",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 35,
				},
				
				[36] = {
					name = "handcuffs",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 36,
				},
				
				[37] = {
					name = "sacouniforme",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 37,
				},
				
				[38] = {
					name = "shield",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 38,
				},
				[39] = {
					name = "locator",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 39,
				},
				[40] = {
					name = "drone_policia",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 40,
				},
				[41] = {
					name = "pulseiraeletronica",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 41,
				},
				[42] = {
					name = "cortadorpulseira",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 42,
				},
				[43] = {
					name = "empty_evidence_bag",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 43,
				},
				[44] = {
					name = "police_stormram",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 44,
				},
				[45] = {
					name = "police_mdt",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 45,
				},
				[46] = {
					name = "radio",
					price = 0,
					amount = 9999999,
					info = {},
					type = "item",
					slot = 46,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
			type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Arsenal',
            blip = false, --or {id = 521, scale = 0.5, color = 3, title = 'LSPD Weapons Market'},
            job = {'police'},
            grade = { 'all' },
			license = 'weapon', -- Require license or not (false or the name of the license)
			licenseError = 'Tens que ter uma licença de porte de arma para usar o armamento da PSP!',
			distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['MercadoNegro'] = {
        label = "Mercado Negro",
        coords = {
            vector3(5599.718, -5666.02, 11.460)
        },
        Shop = {
            items = {
               [1] = {
					name = "fakeid",
					price = 300000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "raspberry",
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "c4_bomb",
					price = 30000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "armor",
					price = 20000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = 'thermite_bomb',
					price = 20000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = 'lockpick',
					price = 20000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = 'cardlvl1',
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = 'cardlvl2',
					price = 25000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = 'hack_usb',
					price = 3500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = 'headbag',
					price = 4000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = 'WEAPON_SNSPISTOL',
					price = 150000,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 11,
				},
				[12] = {
					name = 'pistol_suppressor',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = 'pistol_extendedclip',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = 'pistol_flashlight',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = 'smg_extendedclip',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = 'smg_flashlight',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 16,
				},
				[17] = {
					name = 'smg_scope',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 17,
				},
				[18] = {
					name = 'smg_grip',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 18,
				},
				[19] = {
					name = 'smg_suppressor',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 19,
				},
				[20] = {
					name = 'smg_drummag',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 20,
				},
				[21] = {
					name = 'rifle_extendedclip',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 21,
				},
				[22] = {
					name = 'rifle_drummag',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 22,
				},
				[23] = {
					name = 'rifle_flashlight',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 23,
				},
				[24] = {
					name = 'rifle_scope',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 24,
				},
				[25] = {
					name = 'rifle_grip',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 25,
				},
				[26] = {
					name = 'rifle_suppressor',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 26,
				},
				[27] = {
					name = 'shotgun_suppressor',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 27,
				},
				[28] = {
					name = 'shotgun_flashlight',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 28,
				},
				[29] = {
					name = 'shotgun_grip',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 29,
				},
				[30] = {
					name = 'shotgun_extendedclip',
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 30,
				},
				[31] = {
					name = 'rifle_ammo',
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 31,
				},
				[32] = {
					name = 'smg_ammo',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 32,
				},
				[33] = {
					name = 'shotgun_ammo',
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 33,
				},
				[34] = {
					name = 'pistol_ammo',
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 34,
				},
				[35] = {
					name = 'flare_airdrop',
					price = 400000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 35,
				},
				[36] = {
					name = 'phone_hack',
					price = 200000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 36,
				},
				[37] = {
					name = 'plate',
					price = 200000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 37,
				},
				[38] = {
					name = "handcuffs",
					price = 5000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 38,
				},
				[39] = {
					name = "wetsuit",
					price = 40000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 39,
				},
				[40] = {
					name = "drill",
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 40,
				},
				[41] = {
					name = "gasmask",
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 41,
				},
				[42] = {
					name = "cutter",
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 42,
				},
				[43] = {
					name = "bag",
					price = 600,
					amount = 1000,
					info = {},
					type = "item",
					slot = 43,
				},
				[44] = {
					name = "weapon_bzgas",
					price = 600,
					amount = 1000,
					info = {},
					type = "weapon",
					slot = 44,
				},
				[45] = {
					name = "drone",
					price = 100000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 45,
				},
				[46] = {
					name = "carlockpick",
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 46,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
			type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Mercado Negro',
            blip = false, --or false,
            job = {'all'},
            grade = {'all'},
			license = false, -- Require license or not (false or the name of the license)
			licenseError = 'Tens que ter uma licença!',
			distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['FarmaciaINEM'] = {
        label = "Farmácia",
        coords = {
            vector3(309.12, -567.03, 43.2)
        },
        Shop = {
            items = {
				[1] = {
                    name = "bandage",
                    label = "Ligaduras",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "medkit",
                    label = "Kit Médico",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                },
				[3] = {
                    name = "paramedicbag",
                    label = "Mala Paramédico",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 3,
                },
				
			},
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
			type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Farmácia',
            blip = false, --or {id = 521, scale = 0.5, color = 3, title = 'LSPD Weapons Market'},
            job = {'ambulance'},
            grade = { 'all' },
			license = false, -- Require license or not (false or the name of the license)
			licenseError = 'You dont have the license',
			distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['PecasTunningRedline'] = {
        label = "Peças Tunning",
        coords = {
            vector3(946.4909, -1745.35, 21.025) -- ALTERAR
        },
        Shop = {
            items = {
                [1] = {
					name = "springs",
					price = 1500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "wrench",
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "susp",
					price = 12000,
					amount = 22000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "susp1",
					price = 10000,
					amount = 18000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "susp2",
					price = 15000,
					amount = 15000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "susp3",
					price = 17000,
					amount = 8000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = "susp4",
					price = 13000,
					amount = 4000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = "garett",
					price = 60000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = "nitrous",
					price = 200000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "awd",
					price = 60000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "rwd",
					price = 50000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "fwd",
					price = 55000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "semislick",
					price = 2500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "slick",
					price = 5000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = "race_brakes",
					price = 20000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = "piston",
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 16,
				},
				[17] = {
					name = "rod",
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 17,
				},
				[18] = {
					name = "gear",
					price = 7000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 18,
				},
				[19] = {
					name = "brake_discs",
					price = 3000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 19,
				},
				[20] = {
					name = "brake_caliper",
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 20,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Armário',
            blip = false, --or false,
            job = {'redline'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['ArmarioRedline'] = {
        label = "Armário Redline",
        coords = {
            vector3(-362.521, -98.4524, 39.546)
        },
        Shop = {
           items = {
                [1] = {
					name = "cordareboque",
					price = 200,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "fixtool",
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "tyrekit",
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "tires",
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "brake_pads",
					price = 3500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "oil",
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = "transmission_oil",
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = "shock_absorber",
					price = 5000,
					amount = 300,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = "clutch",
					price = 7000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "air_filter",
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "fuel_filter",
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "spark_plugs",
					price = 1500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "serpentine_belt",
					price = 1500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "scanner",
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				}
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Armário',
            blip = false, --or false,
            job = {'redline'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['ArmarioNorauto'] = {
        label = "Armário Norauto",
        coords = {
            vector3(953.4845, -977.038, 39.499)
        },
        Shop = {
           items = {
                [1] = {
					name = "cordareboque",
					price = 200,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "fixtool",
					price = 2000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "tyrekit",
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "tires",
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "brake_pads",
					price = 3500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "oil",
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = "transmission_oil",
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = "shock_absorber",
					price = 5000,
					amount = 300,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = "clutch",
					price = 7000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "air_filter",
					price = 1000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "fuel_filter",
					price = 500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "spark_plugs",
					price = 1500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "serpentine_belt",
					price = 1500,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "scanner",
					price = 10000,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				}
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Armário',
            blip = false, --or false,
            job = {'mechanic'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['BebidasBahamas'] = {
        label = "Bebidas Bahamas",
        coords = {
            vector3(-1401.40, -598.499, 30.319)
        },
        Shop = {
           items = {
                [1] = {
					name = "water",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "cocacola",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "cafe",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "milk",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "beer",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "energy",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = "icetea",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = "champagne",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = "jager",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "drpepper",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "vodka",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "sumo",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "limonade",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "martini",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = "shot",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = "wine",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 16,
				},
				[17] = {
					name = "mojito",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 17,
				},
				[18] = {
					name = "rhum",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 18,
				},
				[19] = {
					name = "whisky",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 19,
				},
				[20] = {
					name = "tequila",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 20,
				},
				[21] = {
					name = "gintonic",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 21,
				},
				[22] = {
					name = "absinthe",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 22,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Bebidas',
            blip = false, --or false,
            job = {'bahamas'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['BebidasVanilla'] = {
        label = "Bebidas Vanilla",
        coords = {
            vector3(129.9033, -1283.62, 29.269)
        },
        Shop = {
           items = {
                [1] = {
					name = "water",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "cocacola",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "cafe",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "milk",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "beer",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "energy",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = "icetea",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = "champagne",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = "jager",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "drpepper",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "vodka",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "sumo",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "limonade",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "martini",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = "shot",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = "wine",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 16,
				},
				[17] = {
					name = "mojito",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 17,
				},
				[18] = {
					name = "rhum",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 18,
				},
				[19] = {
					name = "whisky",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 19,
				},
				[20] = {
					name = "tequila",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 20,
				},
				[21] = {
					name = "gintonic",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 21,
				},
				[22] = {
					name = "absinthe",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 22,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Bebidas',
            blip = false, --or false,
            job = {'vanilla'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
	
	['BebidasCasino'] = {
        label = "Bebidas Casino",
        coords = {
            vector3(1110.621, 211.6165, -49.44)
        },
        Shop = {
           items = {
                [1] = {
					name = "water",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 1,
				},
				[2] = {
					name = "cocacola",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 2,
				},
				[3] = {
					name = "cafe",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 3,
				},
				[4] = {
					name = "milk",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 4,
				},
				[5] = {
					name = "beer",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 5,
				},
				[6] = {
					name = "energy",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 6,
				},
				[7] = {
					name = "icetea",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 7,
				},
				[8] = {
					name = "champagne",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 8,
				},
				[9] = {
					name = "jager",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 9,
				},
				[10] = {
					name = "drpepper",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 10,
				},
				[11] = {
					name = "vodka",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 11,
				},
				[12] = {
					name = "sumo",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 12,
				},
				[13] = {
					name = "limonade",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 13,
				},
				[14] = {
					name = "martini",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 14,
				},
				[15] = {
					name = "shot",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 15,
				},
				[16] = {
					name = "wine",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 16,
				},
				[17] = {
					name = "mojito",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 17,
				},
				[18] = {
					name = "rhum",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 18,
				},
				[19] = {
					name = "whisky",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 19,
				},
				[20] = {
					name = "tequila",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 20,
				},
				[21] = {
					name = "gintonic",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 21,
				},
				[22] = {
					name = "absinthe",
					price = 5,
					amount = 1000,
					info = {},
					type = "item",
					slot = 22,
				},
            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg =  '~b~E~w~ - Bebidas',
            blip = false, --or false,
            job = {'casino'},
            grade = {'all'},
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'Não tens licença!',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
}