Config = {}

Config.getSharedObject = 'esx:getSharedObject'
Config.setJob = 'esx:setJob'
Config.playerLoaded = 'esx:playerLoaded'

Config.Jobs = { 
  ['police'] = true,
  ['ambulance'] = true,
  ['fbi'] = true,
}

Config.AmmoLabels = {
    ["AMMO_PISTOL"] = "9x19mm Munição de Pistola",
    ["AMMO_SMG"] = "9x19mm Munição de SMG",
    ["AMMO_RIFLE"] = "7.62x39mm Munição de Rifle",
    ["AMMO_MG"] = "7.92x57mm Munição de MG",
    ["AMMO_SHOTGUN"] = "Munição de Shotgun",
    ["AMMO_SNIPER"] = "Munição de Sniper",
}

function SendTextMessage(msg, type)
    if type == 'inform' then 
        exports['Johnny_Notificacoes']:Alert("INFORMAÇÃO", "<span style='color:#c7c7c7'>"..msg.."</span>", 5000, 'info')
    end
    if type == 'error' then 
        exports['Johnny_Notificacoes']:Alert("ERRO", "<span style='color:#c7c7c7'>"..msg.."</span>", 5000, 'error')
    end
    if type == 'success' then 
        exports['Johnny_Notificacoes']:Alert("SUCESSO", "<span style='color:#c7c7c7'>"..msg.."</span>", 5000, 'success')
    end
end

Config.Weapons = {
	-- // WEAPONS
	[GetHashKey("weapon_pumpshotgun_mk2")] 		 = {["name"] = "weapon_pumpshotgun_mk2", 	 	["label"] = "Pump Shotgun MK2", 		["weight"] = 1000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "This is a placeholder description"},
	[GetHashKey("weapon_unarmed")] 				 = {["name"] = "weapon_unarmed", 		 	  	["label"] = "Mão", 						["weight"] = 7000, 		["type"] = "weapon",	["ammotype"] = nil, 					["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Mão."},
	[GetHashKey("weapon_knife")] 				 = {["name"] = "weapon_knife", 			 	  	["label"] = "Faca", 					["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "weapon_knife.png", 	["unique"] = true, 		["useable"] = false, 	["description"] = "Faca."},
	[GetHashKey("weapon_nightstick")] 			 = {["name"] = "weapon_nightstick", 		 	["label"] = "Cassetete", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Cassetete."},
	[GetHashKey("weapon_hammer")] 				 = {["name"] = "weapon_hammer", 			 	["label"] = "Martelo", 					["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Martelo."},
	[GetHashKey("weapon_bat")] 					 = {["name"] = "weapon_bat", 			 	  	["label"] = "Bastão", 					["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Bastão."},
	[GetHashKey("weapon_golfclub")] 			 = {["name"] = "weapon_golfclub", 		 	  	["label"] = "Taco de Golf", 			["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Taco de Golf."},
	[GetHashKey("weapon_crowbar")] 				 = {["name"] = "weapon_crowbar", 		 	  	["label"] = "Pé de Cabra", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Pé de cabra."},
	[GetHashKey("weapon_pistol")] 				 = {["name"] = "weapon_pistol", 			 	["label"] = "Taurus PT92", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_pistol.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_pistol_mk2")] 			 = {["name"] = "weapon_pistol_mk2", 			["label"] = "Pistol Mk II", 			["weight"] = 1000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "pistolmk2.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "This is a placeholder description"},
	[GetHashKey("weapon_combatpistol")] 		 = {["name"] = "weapon_combatpistol", 	 	  	["label"] = "Glock", 					["weight"] = 10000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_combatpistol.png", 	["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_appistol")] 			 = {["name"] = "weapon_appistol", 		 	  	["label"] = "Colt Scamp", 				["weight"] = 10000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_appistol.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_pistol50")] 			 = {["name"] = "weapon_pistol50", 		 	  	["label"] = "Desert Eagle", 			["weight"] = 10000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_pistol50.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_microsmg")] 			 = {["name"] = "weapon_microsmg", 		 	  	["label"] = "Micro UZI", 				["weight"] = 12000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SMG",				["image"] = "weapon_microsmg.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_smg")] 				 	 = {["name"] = "weapon_smg", 			 	  	["label"] = "MP5", 						["weight"] = 12000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SMG",				["image"] = "weapon_smg.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_assaultsmg")] 			 = {["name"] = "weapon_assaultsmg", 		 	["label"] = "Famas", 					["weight"] = 12000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SMG",				["image"] = "weapon_assaultsmg.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_assaultrifle")] 		 = {["name"] = "weapon_assaultrifle", 	 	  	["label"] = "AK-47", 					["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "weapon_assaultrifle.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_assaultrifle_mk2")]      = {["name"] = "weapon_assaultrifle_mk2", 	 	["label"] = "AK-12", 					["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "weapon_assaultrifle_mk2.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_carbinerifle")] 		 = {["name"] = "weapon_carbinerifle", 	 	  	["label"] = "M4A1", 					["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "weapon_carbinerifle.png", 	["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_carbinerifle_mk2")] 	 = {["name"] = "weapon_carbinerifle_mk2", 	 	["label"] = "AR-12", 					["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "weapon_carbinerifle_mk2.png", 	["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_advancedrifle")] 		 = {["name"] = "weapon_advancedrifle", 	 	  	["label"] = "AUG", 						["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "weapon_advancedrifle.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_mg")] 					 = {["name"] = "weapon_mg", 				 	["label"] = "MG", 						["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_MG",				["image"] = "weapon_mg.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_combatmg")] 			 = {["name"] = "weapon_combatmg", 		 	  	["label"] = "Combat MG", 				["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_MG",				["image"] = "weapon_combatmg.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_pumpshotgun")] 			 = {["name"] = "weapon_pumpshotgun", 	 	  	["label"] = "Shotgun XM1014", 			["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "weapon_pumpshotgun.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_sawnoffshotgun")] 		 = {["name"] = "weapon_sawnoffshotgun", 	 	["label"] = "Sawed-Off", 				["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "weapon_sawnoffshotgun.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_assaultshotgun")] 		 = {["name"] = "weapon_assaultshotgun", 	 	["label"] = "UTS-15", 					["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "weapon_assaultshotgun.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_bullpupshotgun")] 		 = {["name"] = "weapon_bullpupshotgun", 	 	["label"] = "Bullpup Shotgun", 			["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "weapon_bullpupshotgun.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_stungun")] 				 = {["name"] = "weapon_stungun", 		 	  	["label"] = "Taser", 					["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "weapon_stungun.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_sniperrifle")] 			 = {["name"] = "weapon_sniperrifle", 	 	  	["label"] = "AWP", 						["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SNIPER",			["image"] = "weapon_sniperrifle.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_sniperrifle_mk2")] 		 = {["name"] = "weapon_sniperrifle_mk2", 	 	["label"] = "AWP MK2", 					["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SNIPER",			["image"] = "weapon_sniperrifle_mk2.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_heavysniper")] 			 = {["name"] = "weapon_heavysniper", 	 	  	["label"] = "Sniper Knights SR-25", 	["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SNIPER",			["image"] = "weapon_heavysniper.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_remotesniper")] 		 = {["name"] = "weapon_remotesniper", 	 	  	["label"] = "Remote Sniper", 			["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SNIPER_REMOTE",	["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_grenadelauncher")] 		 = {["name"] = "weapon_grenadelauncher", 	  	["label"] = "Grenade Launcher", 		["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_GRENADELAUNCHER",	["image"] = "weapon_grenadelauncher.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_grenadelauncher_smoke")] = {["name"] = "weapon_grenadelauncher_smoke", 	["label"] = "Smoke Grenade Launcher", 	["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_GRENADELAUNCHER",	["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_rpg")] 					 = {["name"] = "weapon_rpg", 			      	["label"] = "RPG", 						["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RPG",				["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_minigun")] 				 = {["name"] = "weapon_minigun", 		      	["label"] = "Minigun", 					["weight"] = 20000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_MINIGUN",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_grenade")] 				 = {["name"] = "weapon_grenade", 		      	["label"] = "Grenade", 					["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_stickybomb")] 			 = {["name"] = "weapon_stickybomb", 		    ["label"] = "C4", 						["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "stickybomb.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_smokegrenade")] 		 = {["name"] = "weapon_smokegrenade", 	      	["label"] = "Smoke Grenade", 			["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_bzgas")] 				 = {["name"] = "weapon_bzgas", 			      	["label"] = "Gás Lacrimogénio", 		["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_molotov")] 				 = {["name"] = "weapon_molotov", 		      	["label"] = "Molotov", 					["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_fireextinguisher")] 	 = {["name"] = "weapon_fireextinguisher",      	["label"] = "Extintor", 				["weight"] = 10000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_flashlight")] 			 = {["name"] = "weapon_flashlight",      		["label"] = "Lanterna", 				["weight"] = 3000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "weapon_flashlight.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_petrolcan")] 			 = {["name"] = "weapon_petrolcan", 		 	  	["label"] = "Galão de Combustível", 	["weight"] = 3000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PETROLCAN",		["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_briefcase")] 			 = {["name"] = "weapon_briefcase", 		 	  	["label"] = "Briefcase", 				["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_briefcase_02")] 		 = {["name"] = "weapon_briefcase_02", 	 	  	["label"] = "Briefcase2", 				["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_ball")] 				 = {["name"] = "weapon_ball", 			 	  	["label"] = "Ball", 					["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_BALL",				["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_flare")] 				 = {["name"] = "weapon_flare", 			 	  	["label"] = "Flare pistol", 			["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_FLARE",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_snspistol")] 			 = {["name"] = "weapon_snspistol", 		 	  	["label"] = "Pistola SNS", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_snspistol.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_bottle")] 				 = {["name"] = "weapon_bottle", 			 	["label"] = "Bottle", 					["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_gusenberg")] 			 = {["name"] = "weapon_gusenberg", 		 	  	["label"] = "Tommy Gun", 				["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_MG",				["image"] = "weapon_gusenberg.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_specialcarbine")] 		 = {["name"] = "weapon_specialcarbine", 	 	["label"] = "HK G36", 					["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "weapon_specialcarbine.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_heavypistol")] 			 = {["name"] = "weapon_heavypistol", 	 	  	["label"] = "Pistola Pesada", 			["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_heavypistol.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_bullpuprifle")] 		 = {["name"] = "weapon_bullpuprifle", 	 	  	["label"] = "QBZ", 						["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_dagger")] 				 = {["name"] = "weapon_dagger", 			 	["label"] = "Punhal", 					["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_vintagepistol")] 		 = {["name"] = "weapon_vintagepistol", 	 	  	["label"] = "FN Model 1910", 			["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_vintagepistol.png", ["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_firework")] 			 = {["name"] = "weapon_firework", 		 	  	["label"] = "Firework Launcher", 		["weight"] = 10000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_musket")] 			     = {["name"] = "weapon_musket", 			 	["label"] = "Espingarda", 				["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_heavyshotgun")] 		 = {["name"] = "weapon_heavyshotgun", 	 	  	["label"] = "Saiga 12", 				["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "weapon_heavyshotgun.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_marksmanrifle")] 		 = {["name"] = "weapon_marksmanrifle", 	 	  	["label"] = "Marksman Rifle", 			["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SNIPER",			["image"] = "weapon_marksmanrifle.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_hominglauncher")] 		 = {["name"] = "weapon_hominglauncher", 	 	["label"] = "Homing Launcher", 			["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_STINGER",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_proxmine")] 			 = {["name"] = "weapon_proxmine", 		 	  	["label"] = "Proxmine Grenade", 		["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_snowball")] 		     = {["name"] = "weapon_snowball", 		 	  	["label"] = "Snowball", 				["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_flaregun")] 			 = {["name"] = "weapon_flaregun", 		 	  	["label"] = "Pistola Sinalizadora", 	["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_FLARE",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_garbagebag")] 			 = {["name"] = "weapon_garbagebag", 		 	["label"] = "Garbagebag", 				["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_handcuffs")] 			 = {["name"] = "weapon_handcuffs", 		 	  	["label"] = "Handcuffs", 				["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Algemas."},
	[GetHashKey("weapon_combatpdw")] 			 = {["name"] = "weapon_combatpdw", 		 	  	["label"] = "SIG MPX", 					["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SMG",				["image"] = "weapon_combatpdw.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_marksmanpistol")] 		 = {["name"] = "weapon_marksmanpistol", 	 	["label"] = "Trabuco", 					["weight"] = 12000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_knuckle")] 				 = {["name"] = "weapon_knuckle", 		 	  	["label"] = "Soco Inglês", 				["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_NONE",				["image"] = "weapon_knuckle.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_hatchet")] 				 = {["name"] = "weapon_hatchet", 		 	  	["label"] = "Hatchet", 					["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_NONE",				["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_railgun")] 				 = {["name"] = "weapon_railgun", 		 	  	["label"] = "Railgun", 					["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_machete")] 				 = {["name"] = "weapon_machete", 		 	  	["label"] = "Facão", 					["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_machinepistol")] 		 = {["name"] = "weapon_machinepistol", 	 	  	["label"] = "Tec-9", 					["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_switchblade")] 			 = {["name"] = "weapon_switchblade", 	 	  	["label"] = "Canivete", 				["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_NONE",				["image"] = "weapon_switchblade.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_revolver")] 			 = {["name"] = "weapon_revolver", 		 	  	["label"] = "Revólver", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_revolver.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_navyrevolver")] 		 = {["name"] = "weapon_navyrevolver", 	  		["label"] = "Colt 1851", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_navyrevolver.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_revolver_mk2")] 		 = {["name"] = "weapon_revolver_mk2", 	  		["label"] = "Revólver MK II", 			["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_PISTOL",			["image"] = "weapon_revolver_mk2.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_dbshotgun")] 			 = {["name"] = "weapon_dbshotgun", 		 	  	["label"] = "DB Shotgun", 				["weight"] = 12000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Munição."},
	[GetHashKey("weapon_compactrifle")] 		 = {["name"] = "weapon_compactrifle", 	 	  	["label"] = "Mini Draco", 				["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_RIFLE",			["image"] = "weapon_compactrifle.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_battleaxe")] 			 = {["name"] = "weapon_battleaxe", 		 	  	["label"] = "Battle Axe", 				["weight"] = 5000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_compactlauncher")] 		 = {["name"] = "weapon_compactlauncher",  	  	["label"] = "Compact Launcher", 		["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_minismg")] 				 = {["name"] = "weapon_minismg", 		 	  	["label"] = "MAC-10", 					["weight"] = 12000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SMG",				["image"] = "weapon_minismg.png", 	["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_pipebomb")] 			 = {["name"] = "weapon_pipebomb", 		 	  	["label"] = "Pipe bom", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_poolcue")] 				 = {["name"] = "weapon_poolcue", 		 	  	["label"] = "Poolcue", 					["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_wrench")] 				 = {["name"] = "weapon_wrench", 			 	["label"] = "Chave de Fendas", 			["weight"] = 2000, 		["type"] = "weapon", 	["ammotype"] = nil,						["image"] = "placeholder.png", 		["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_autoshotgun")] 		 	 = {["name"] = "weapon_autoshotgun", 	 		["label"] = "Benelli M4", 				["weight"] = 15000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_SHOTGUN",			["image"] = "sweepershotgun.png", 	["unique"] = true, 		["useable"] = false, 	["description"] = "Arma de calibre alto."},
	[GetHashKey("weapon_raypistol")] 		 	 = {["name"] = "weapon_raypistol", 	 			["label"] = "Ray Pistol", 				["weight"] = 7000, 		["type"] = "weapon", 	["ammotype"] = "AMMO_NONE",				["image"] = "weapon_raypistol.png", ["unique"] = true, 		["useable"] = false, 		["description"] = "Arma de calibre alto."},
}
