DROP TABLE IF EXISTS `battlepass`;
CREATE TABLE `battlepass` (
  `identifier` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `xp` int(11) DEFAULT 0,
  `level` int(11) DEFAULT 0,
  `premium` tinyint(1) NOT NULL DEFAULT 0,
  `std_redeem_1` tinyint(1) NOT NULL DEFAULT 0,
  `std_redeem_2` tinyint(1) NOT NULL DEFAULT 0,
  `std_redeem_3` tinyint(1) NOT NULL DEFAULT 0,
  `std_redeem_4` tinyint(1) NOT NULL DEFAULT 0,
  `std_redeem_5` tinyint(1) NOT NULL DEFAULT 0,
  `prm_redeem_1` tinyint(1) NOT NULL DEFAULT 0,
  `prm_redeem_2` tinyint(1) NOT NULL DEFAULT 0,
  `prm_redeem_3` tinyint(1) NOT NULL DEFAULT 0,
  `prm_redeem_4` tinyint(1) NOT NULL DEFAULT 0,
  `prm_redeem_5` tinyint(1) NOT NULL DEFAULT 0,
  `task_1` tinyint(1) NOT NULL DEFAULT 0,
  `task_2` tinyint(1) NOT NULL DEFAULT 0,
  `task_3` tinyint(1) NOT NULL DEFAULT 0,
  `task_4` tinyint(1) NOT NULL DEFAULT 0,
  `task_5` tinyint(1) NOT NULL DEFAULT 0,
  `task_6` tinyint(1) NOT NULL DEFAULT 0,
  `task_7` tinyint(1) NOT NULL DEFAULT 0,
  `task_8` tinyint(1) NOT NULL DEFAULT 0,
  `task_9` tinyint(1) NOT NULL DEFAULT 0,
  `task_10` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`identifier`),
  UNIQUE KEY `identifier` (`identifier`,`xp`,`level`,`premium`,`std_redeem_1`,`std_redeem_2`),
  UNIQUE KEY `xp` (`xp`,`level`,`premium`,`std_redeem_1`,`std_redeem_2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;